version: "3.7"

services:
 db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
        POSTGRES_DB: postgres:13-alpine
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: ${ONE_PIECE}
    volumes:
    - /var/lib/postgresql/data
    ports:
    - 5432:5432